### ISSUE TITLE
İndirme klasörü seçme çalışmıyor.

### ISSUE THREAD

**Issue by Mustafa-eksi** [KebabLord/turkanime-indirici#44]
**Sorunu açıklayın**
1. turkanime'yi başlatın.
2. ayarlar'ı seçin
3. "İndirilenler klasörünü seç" seçeneğini seçin
4. Uygulama hata veriyor ve çıkıyor.
Verdiği hata:
```
Traceback (most recent call last):
  File "/home/mustafa/.local/lib/python3.10/site-packages/easygui/boxes/utils.py", line 29, in <module>
    import tkinter as tk  # python3
ModuleNotFoundError: No module named 'tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mustafa/.local/lib/python3.10/site-packages/easygui/boxes/utils.py", line 36, in <module>
    import Tkinter as tk  # python2
ModuleNotFoundError: No module named 'Tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mustafa/.local/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 15, in <module>
    from . import utils as ut
  File "/home/mustafa/.local/lib/python3.10/site-packages/easygui/boxes/utils.py", line 43, in <module>
    raise ImportError("Unable to find tkinter package.")
ImportError: Unable to find tkinter package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mustafa/.local/bin/turkanime", line 5, in <module>
    from turkanime_api.cli.turkanime import run
  File "/home/mustafa/.local/lib/python3.10/site-packages/turkanime_api/cli/turkanime.py", line 126, in <module>
    from easygui import diropenbox
  File "/home/mustafa/.local/lib/python3.10/site-packages/easygui/__init__.py", line 34, in <module>
    from .boxes.button_box import buttonbox
  File "/home/mustafa/.local/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 18, in <module>
    import global_state
ModuleNotFoundError: No module named 'global_state'
```

**Lütfen aşağıdaki bilgileri doldurun:**
 - İşletim Sistemi: Linux (PopOS!)
 - Kullandığınız Sürüm: kaynak kodundan da denedim pipten de
 - Versiyon https://github.com/KebabLord/turkanime-indirici/tree/582c4127c492507768f9cfbdd43253c6de4fa4a1

**Comment by Mustafa-eksi** [comment]
Muhtemelen requirements.txt'de bazı modüller eksik

**Comment by Mustafa-eksi** [comment]
Sorunu çözdüm:
sadece tkinter paketini yüklemem gerekiyormuş, aşağıdaki komutla yükleyince tüm problem çözüldü
```
$ sudo apt-get install python3-tk
```
