### ISSUE TITLE
Paralel indirme hatası

### ISSUE THREAD

**Issue by barkeser2002** [KebabLord/turkanime-indirici#52]
**Sorunu açıklayın**
çıktı:
```
? Bölüm seç done (20 selections)
 - Paralel indirme aktif. (max=3)


1. video hazırlanıyor:
Video aktif, başlatılıyor!

Traceback (most recent call last):
  File "C:\Users\bkese\Desktop\turkanime-indirici\turkanime.py", line 115, in <module>
    anime.multi_indir(max_dl)
  File "C:\Users\bkese\Desktop\turkanime-indirici\turkanime_api\anime.py", line 162, in multi_indir
    cmds.append()
TypeError: list.append() takes exactly one argument (0 given)
```

**Lütfen aşağıdaki bilgileri doldurun:**
 - İşletim Sistemi: windows
 - Kullandığınız Sürüm: kaynak kod
 - Versiyon güncel kaynak kod
 
 not: tekli indir'e geçince sıkıntı yok

**Comment by barkeser2002** [comment]
https://github.com/KebabLord/turkanime-indirici/blob/c85030c3accb9c1b3dce75ea2aff6057a61abd40/turkanime_api/anime.py#L162

bu kodu şununladeğiştirince windows için çalışır hale geldi
`cmds.append(cmd)`
