### ISSUE TITLE
Hata ??

### ISSUE THREAD

**Issue by hakankarakis** [KebabLord/turkanime-indirici#56]
Hocam yeni sürümü acmaya calistigimda söyle bi hata aliyorum ...
bir önceki sürüm gayet normal calisiyor ama yenisini indirmeye calistigim zaman hata veriyor...

Traceback (most recent call last):
File "turkanime.py”, line 18, in <module> 
File "<frozen importlib._bootstrap>", line 1178, in _find_and_load 
File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked 
File "<frozen importlib._bootstrap>", line 690, in _Toad_unlocked 
File "PyInstaller\loader\pyimod@2_importers.py", line 385, in exec_module 
File "turkanime_api\_init__.py”, line 6, in <module> 
Tile "<frozen importlib._boststrap>", line 1178, in _find_and_load 
File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked 
File "<frozen importlib._bootstrap>", line 690, in _Toad_unlocked 
File "PyInstaller\loader\pyimod@2_importers.py“, line 385, in exec_module 
File "turkanime_api\version.py", line 42, in <module> 

Valueerror: invalid literal for int() with base 10: 'v7'

[11152] Failed to execute script "turkanime" due to unhandled exception!

 - İşletim Sistemi: Windows 10
 - Kullandığınız Sürüm:EXE
 - Versiyon 7.1.1

**Comment by KebabLord** [comment]
sorunun hala devam edip etmediğini tekrar kontrol eder misin?

**Comment by hakankarakis** [comment]
baktim hocam aciliyor ama ayarlara girince ayni hatayi verip kapaniyor

**Comment by KebabLord** [comment]
ayalarda "paralel anime indirme ayarı" bulunmamasından mütevellit configparser hata veriyor
```python
? İşlemi seç Ayarlar
Traceback (most recent call last):
  File "configparser.py", line 804, in get
  File "collections\__init__.py", line 1004, in __getitem__
  File "collections\__init__.py", line 996, in __missing__
KeyError: 'aynı anda indirme sayısı'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "turkanime.py", line 143, in <module>
  File "configparser.py", line 807, in get
configparser.NoOptionError: No option 'aynı anda indirme sayısı' in section: 'TurkAnime'
[1588] Failed to execute script 'turkanime' due to unhandled exception!
Program kapatılıyor..
```

Geri bildirimin için gerçekten çok teşekkür ederim, son release'i sildim, önceki versiyonu kullanmaya devam edebilirsin. Güncel release'i radikal bir güncellemeyle birlikte hazır olduğunda yayınlayacağım.

Bu issue da hatalar giderilinceye dek açık kalabilir.
