### ISSUE TITLE
Kurulum hatası

### ISSUE THREAD

**Issue by yakan12** [KebabLord/turkanime-indirici#57]
programı kurmaya çalıştığımda aşşağıdaki hatayı alıyorum;

⠹ Sürücü başlatılıyor.. ----------------------------------------

x geckodriver bulunamadı.
x youtube-dl bulunamadı.
x mpv bulunamadı.

Belirtilen program yada programlar program dizininde yada sistem PATH'ında bulunamadı.
? Otomatik kurulsun mu? Yes
[18:31:09] İndiriliyor mpv-i686-20221218-git-f9d0b0c.7z                                                                                                dosyalar.pyc:173
           HATA: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:992)>                      dosyalar.pyc:177
mpv-i686-20221218-git-f9d0b0c.7z ----------------------------------------------------------------------------------------------------- 0.0% • 0/100 bytes • ? • -:--:--
                                                                                                                                                       dosyalar.pyc:140

           Siteye ulaşılamıyor: https://pilotfiber.dl.sourceforge.net
           Gereksinimleri manuel olarak kurmak için klavuz.html'i oku.
Traceback (most recent call last):
  File "turkanime.py", line 20, in <module>
  File "turkanime_api\tools.py", line 54, in gereksinim_kontrol
  File "turkanime_api\dosyalar.py", line 118, in __init__
  File "turkanime_api\dosyalar.py", line 143, in fetch_gereksinim
NameError: name 'exit' is not defined
[4208] Failed to execute script 'turkanime' due to unhandled exception!

**Comment by KebabLord** [comment]
problem hala devam ediyor mu?

**Comment by yakan12** [comment]
hayır ama az önce acaba firefox yerine opera.exe'yi gösterirsem ne olur diye merak edip denedim.... şu an program açılmıyor....onun yerine şu hatayı alıyorum;

⠏ Sürücü başlatılıyor.. ----------------------------------------
Traceback (most recent call last):
File "turkanime.py", line 21, in <module>
File "turkanime_api\tools.py", line 80, in webdriver_hazirla
File "selenium\webdriver\firefox\webdriver.py", line 170, in __init__
File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
File "selenium\webdriver\remote\webdriver.py", line 321, in execute
File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable

[9600] Failed to execute script 'turkanime' due to unhandled exception!

**Comment by KebabLord** [comment]
:D ilginç bir girişim.
düzeltmek için `C:/Users/kullanici_adin/TurkAnimu/ayarlar.ini` dosyasını komple silebilir veya oradaki firefox konumu satırını silebilirsin. Uygulamayı yeniden başlattığında bu kez firefox'u seçmelisin

**Comment by yakan12** [comment]
düzeldi teşekkürler xd
