### ISSUE TITLE
Çoklu Açma

### ISSUE THREAD

**Issue by Prohibitive** [KebabLord/turkanime-indirici#66]
Üç tane açtığımda ikisi şu şekilde hata veriyor. ama indirme devam ediyor.
`
ERROR:concurrent.futures:exception calling callback for <Future at 0x1788ffddd48 state=finished returned NoneType>
Traceback (most recent call last):
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
`

**Lütfen aşağıdaki bilgileri doldurun:**
 - İşletim Sistemi: windows 10
 - Kullandığınız Sürüm: kaynak kod
 - Versiyon 8.2.2

**Comment by KebabLord** [comment]
muhtemelen concurrent.futures çakışıyor ve RAM'in de yetmiyordur.

script'in 3 kere açılma gibi bir desteği yok, dolayısıyla düzeltilmeyecek bir problem.
