### ISSUE TITLE
JSONDECODE

### ISSUE THREAD

**Issue by Prohibitive** [KebabLord/turkanime-indirici#68]
**Sorunu açıklayın**
Low disk uyarısından sonra (sanırım yarıda kesilmesinden kaynaklı) aşağıdaki hatayı almaktayım.
`
Traceback (most recent call last):
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\site-packages\turkanime_api\cli\__main__.py", line 247, in <module>
    main()
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\site-packages\turkanime_api\cli\__main__.py", line 243, in main
    menu_loop(driver)
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\site-packages\turkanime_api\cli\__main__.py", line 126, in menu_loop
    choices, recent = eps_to_choices(anime.bolumler, mark_type="indirildi")
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\site-packages\turkanime_api\cli\__main__.py", line 33, in eps_to_choices
    gecmis_ = Dosyalar().gecmis
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\site-packages\turkanime_api\cli\dosyalar.py", line 93, in gecmis
    return json.load(fp)
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Prohibitive\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1321 column 7 (char 47829)

`

**Lütfen aşağıdaki bilgileri doldurun:**
 - İşletim Sistemi: Windows 10
 - Kullandığınız Sürüm: kaynak kod
 - Versiyon 8.2.2
@KebabLord

**Comment by Prohibitive** [comment]
eskiden göndermiş olduğun json u indirip üstüne yazdırdığımda eski haline geldi lakin bunu yazmamdaki sebep zamanında yaşadığım bu şeyi fixleyen kodu ekledim demiş olmandı.
Saygılarımla

**Comment by KebabLord** [comment]
@Prohibitive geri bildirim için teşekkürler, eklediğim çözümün işe yaramamış olması üzdü, düzelteceğim
