### ISSUE TITLE
İndirme Klasörünü Seçerken global_state hatası.

### ISSUE THREAD

**Issue by toprak** [KebabLord/turkanime-indirici#9]
Kullandığım distro ubuntu 20.04, tüm gereksinimler yüklü aldıgım hata
```Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 37, in <module>
    import _tkinter
ModuleNotFoundError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/easygui/boxes/utils.py", line 29, in <module>
    import tkinter as tk  # python3
  File "/usr/lib/python3.6/tkinter/__init__.py", line 39, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/easygui/boxes/utils.py", line 36, in <module>
    import Tkinter as tk  # python2
ModuleNotFoundError: No module named 'Tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/easygui/boxes/button_box.py", line 15, in <module>
    from . import utils as ut
  File "/usr/local/lib/python3.6/dist-packages/easygui/boxes/utils.py", line 43, in <module>
    raise ImportError("Unable to find tkinter package.")
ImportError: Unable to find tkinter package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "turkanime.py", line 85, in <module>
    from easygui import diropenbox
  File "/usr/local/lib/python3.6/dist-packages/easygui/__init__.py", line 34, in <module>
    from .boxes.button_box import buttonbox
  File "/usr/local/lib/python3.6/dist-packages/easygui/boxes/button_box.py", line 18, in <module>
    import global_state
ModuleNotFoundError: No module named 'global_state' ```
Hata'da bahsettiği paketi yükledim sonuç aynı.

**Comment by KebabLord** [comment]
Easygui ve tkinteri yeniden kurabilir yada python3.7'yi kullanmayı deneyebilirsin. Problem kütüphaneye ait olduğu için şimdilik kapıyorum. Bu arada easygui'nin genelde arızalı olduğunun farkındayım, en kısa sürede yeni bir kütüphaneye geçmeli.

**Comment by toprak** [comment]
3.8 kullanarak da denedim neyse, şuanlık downloader'ın yüklü olduğu klasöre yüklese de olur.

**Comment by KebabLord** [comment]
> 3.8 kullanarak da denedim neyse, şuanlık downloader'ın yüklü olduğu klasöre yüklese de olur.
programın bulunduğu dizinde `config.ini` var, 4.satırdan manuel olarak indirilenler klasörünü elle girebilirsin.
